import { Character } from "@/utils/types";

export const characters: Character[] = [
  {
    name: "Juri",
    bio: "A contractor for a PMC, Luke uses his elite military background to teach mixed martial arts. His days off are spent eating junk food, playing video games, and fighting, but make no mistake—Luke plays to win.",
    like: "Travelling, PC games, wacky T-shirts",
    notlike: "Horror games",
    height: "6'1",
    weight: "198 lbs",
  },
  {
    name: "Luke",
    bio: "A contractor for a PMC, Luke uses his elite military background to teach mixed martial arts. His days off are spent eating junk food, playing video games, and fighting, but make no mistake—Luke plays to win.",
    like: "Travelling, PC games, wacky T-shirts",
    notlike: "Horror games",
    height: "6'1",
    weight: "198 lbs",
  },
  {
    name: "Ken",
    bio: "A contractor for a PMC, Luke uses his elite military background to teach mixed martial arts. His days off are spent eating junk food, playing video games, and fighting, but make no mistake—Luke plays to win.",
    like: "Travelling, PC games, wacky T-shirts",
    notlike: "Horror games",
    height: "6'1",
    weight: "198 lbs",
  },
  {
    name: "Rashid",
    bio: "A contractor for a PMC, Luke uses his elite military background to teach mixed martial arts. His days off are spent eating junk food, playing video games, and fighting, but make no mistake—Luke plays to win.",
    like: "Travelling, PC games, wacky T-shirts",
    notlike: "Horror games",
    height: "6'1",
    weight: "198 lbs",
  },
  {
    name: "Jamie",
    bio: "A contractor for a PMC, Luke uses his elite military background to teach mixed martial arts. His days off are spent eating junk food, playing video games, and fighting, but make no mistake—Luke plays to win.",
    like: "Travelling, PC games, wacky T-shirts",
    notlike: "Horror games",
    height: "6'1",
    weight: "198 lbs",
  },
  {
    name: "JP",
    bio: "A contractor for a PMC, Luke uses his elite military background to teach mixed martial arts. His days off are spent eating junk food, playing video games, and fighting, but make no mistake—Luke plays to win.",
    like: "Travelling, PC games, wacky T-shirts",
    notlike: "Horror games",
    height: "6'1",
    weight: "198 lbs",
  },
  {
    name: "Manon",
    bio: "A contractor for a PMC, Luke uses his elite military background to teach mixed martial arts. His days off are spent eating junk food, playing video games, and fighting, but make no mistake—Luke plays to win.",
    like: "Travelling, PC games, wacky T-shirts",
    notlike: "Horror games",
    height: "6'1",
    weight: "198 lbs",
  },
  {
    name: "Juri",
    bio: "A contractor for a PMC, Luke uses his elite military background to teach mixed martial arts. His days off are spent eating junk food, playing video games, and fighting, but make no mistake—Luke plays to win.",
    like: "Travelling, PC games, wacky T-shirts",
    notlike: "Horror games",
    height: "6'1",
    weight: "198 lbs",
  },
  {
    name: "Juri",
    bio: "A contractor for a PMC, Luke uses his elite military background to teach mixed martial arts. His days off are spent eating junk food, playing video games, and fighting, but make no mistake—Luke plays to win.",
    like: "Travelling, PC games, wacky T-shirts",
    notlike: "Horror games",
    height: "6'1",
    weight: "198 lbs",
  },
  {
    name: "Juri",
    bio: "A contractor for a PMC, Luke uses his elite military background to teach mixed martial arts. His days off are spent eating junk food, playing video games, and fighting, but make no mistake—Luke plays to win.",
    like: "Travelling, PC games, wacky T-shirts",
    notlike: "Horror games",
    height: "6'1",
    weight: "198 lbs",
  },
  {
    name: "Juri",
    bio: "A contractor for a PMC, Luke uses his elite military background to teach mixed martial arts. His days off are spent eating junk food, playing video games, and fighting, but make no mistake—Luke plays to win.",
    like: "Travelling, PC games, wacky T-shirts",
    notlike: "Horror games",
    height: "6'1",
    weight: "198 lbs",
  },
  {
    name: "Juri",
    bio: "A contractor for a PMC, Luke uses his elite military background to teach mixed martial arts. His days off are spent eating junk food, playing video games, and fighting, but make no mistake—Luke plays to win.",
    like: "Travelling, PC games, wacky T-shirts",
    notlike: "Horror games",
    height: "6'1",
    weight: "198 lbs",
  },
  {
    name: "Juri",
    bio: "A contractor for a PMC, Luke uses his elite military background to teach mixed martial arts. His days off are spent eating junk food, playing video games, and fighting, but make no mistake—Luke plays to win.",
    like: "Travelling, PC games, wacky T-shirts",
    notlike: "Horror games",
    height: "6'1",
    weight: "198 lbs",
  },
  {
    name: "Juri",
    bio: "A contractor for a PMC, Luke uses his elite military background to teach mixed martial arts. His days off are spent eating junk food, playing video games, and fighting, but make no mistake—Luke plays to win.",
    like: "Travelling, PC games, wacky T-shirts",
    notlike: "Horror games",
    height: "6'1",
    weight: "198 lbs",
  },
  {
    name: "Juri",
    bio: "A contractor for a PMC, Luke uses his elite military background to teach mixed martial arts. His days off are spent eating junk food, playing video games, and fighting, but make no mistake—Luke plays to win.",
    like: "Travelling, PC games, wacky T-shirts",
    notlike: "Horror games",
    height: "6'1",
    weight: "198 lbs",
  },
  {
    name: "Juri",
    bio: "A contractor for a PMC, Luke uses his elite military background to teach mixed martial arts. His days off are spent eating junk food, playing video games, and fighting, but make no mistake—Luke plays to win.",
    like: "Travelling, PC games, wacky T-shirts",
    notlike: "Horror games",
    height: "6'1",
    weight: "198 lbs",
  },
  {
    name: "Juri",
    bio: "A contractor for a PMC, Luke uses his elite military background to teach mixed martial arts. His days off are spent eating junk food, playing video games, and fighting, but make no mistake—Luke plays to win.",
    like: "Travelling, PC games, wacky T-shirts",
    notlike: "Horror games",
    height: "6'1",
    weight: "198 lbs",
  },
  {
    name: "Juri",
    bio: "A contractor for a PMC, Luke uses his elite military background to teach mixed martial arts. His days off are spent eating junk food, playing video games, and fighting, but make no mistake—Luke plays to win.",
    like: "Travelling, PC games, wacky T-shirts",
    notlike: "Horror games",
    height: "6'1",
    weight: "198 lbs",
  },
  {
    name: "Juri",
    bio: "A contractor for a PMC, Luke uses his elite military background to teach mixed martial arts. His days off are spent eating junk food, playing video games, and fighting, but make no mistake—Luke plays to win.",
    like: "Travelling, PC games, wacky T-shirts",
    notlike: "Horror games",
    height: "6'1",
    weight: "198 lbs",
  },
];
